#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("diagram.Resource", IsApplication=true)]

namespace diagram
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int linearLayout1 = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int linearLayout2 = 2130968583;
			
			// aapt resource value: 0x7f04000f
			public const int linearLayout3 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int linearLayout4 = 2130968592;
			
			// aapt resource value: 0x7f040014
			public const int linearLayout5 = 2130968596;
			
			// aapt resource value: 0x7f040018
			public const int linearLayout6 = 2130968600;
			
			// aapt resource value: 0x7f04001c
			public const int linearLayout7 = 2130968604;
			
			// aapt resource value: 0x7f04000b
			public const int linearLayout8 = 2130968587;
			
			// aapt resource value: 0x7f040021
			public const int linearLayout9 = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int scrollView1 = 2130968608;
			
			// aapt resource value: 0x7f040005
			public const int space1 = 2130968581;
			
			// aapt resource value: 0x7f040013
			public const int space2 = 2130968595;
			
			// aapt resource value: 0x7f040017
			public const int space3 = 2130968599;
			
			// aapt resource value: 0x7f04001b
			public const int space4 = 2130968603;
			
			// aapt resource value: 0x7f040023
			public const int space5 = 2130968611;
			
			// aapt resource value: 0x7f040025
			public const int space6 = 2130968613;
			
			// aapt resource value: 0x7f040027
			public const int space7 = 2130968615;
			
			// aapt resource value: 0x7f040008
			public const int spinner1 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int spinner2 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int spinner3 = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int textClock1 = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int textClock2 = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int textView1 = 2130968576;
			
			// aapt resource value: 0x7f040016
			public const int textView10 = 2130968598;
			
			// aapt resource value: 0x7f04001a
			public const int textView11 = 2130968602;
			
			// aapt resource value: 0x7f04001e
			public const int textView12 = 2130968606;
			
			// aapt resource value: 0x7f04000d
			public const int textView13 = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int textView14 = 2130968588;
			
			// aapt resource value: 0x7f04001f
			public const int textView15 = 2130968607;
			
			// aapt resource value: 0x7f040022
			public const int textView16 = 2130968610;
			
			// aapt resource value: 0x7f040024
			public const int textView17 = 2130968612;
			
			// aapt resource value: 0x7f040026
			public const int textView18 = 2130968614;
			
			// aapt resource value: 0x7f040028
			public const int textView19 = 2130968616;
			
			// aapt resource value: 0x7f040003
			public const int textView2 = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int textView3 = 2130968582;
			
			// aapt resource value: 0x7f04000e
			public const int textView4 = 2130968590;
			
			// aapt resource value: 0x7f040011
			public const int textView5 = 2130968593;
			
			// aapt resource value: 0x7f040015
			public const int textView6 = 2130968597;
			
			// aapt resource value: 0x7f040019
			public const int textView7 = 2130968601;
			
			// aapt resource value: 0x7f04001d
			public const int textView8 = 2130968605;
			
			// aapt resource value: 0x7f040012
			public const int textView9 = 2130968594;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int initilizing = 2130903042;
			
			// aapt resource value: 0x7f030006
			public const int initilizingCar = 2130903046;
			
			// aapt resource value: 0x7f030004
			public const int initilizingStation = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int initilizingTime = 2130903045;
			
			// aapt resource value: 0x7f030003
			public const int initilizingWeek = 2130903043;
			
			// aapt resource value: 0x7f030001
			public const int label1 = 2130903041;
			
			// aapt resource value: 0x7f030007
			public const int label2 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int label3 = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int label4 = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int label5 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int label6 = 2130903051;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
